### ISSUE TITLE
"Back to Listings" link doesn't work after Watching/Unwatching a Listing

### ISSUE THREAD

**Issue by femmestem** [erikcaineolson/HARE#20]
From the detailed listing view (`Listing#show`) the user can click a `"Back to Listings"` link to return to the `Listing#index`. This preserves filtered categories a user has applied on the `Listing#index`. The link does _not_ work as intended after the user clicks the `Watch`/`Unwatch` button to un/follow the listing; the `HTTP_REFERER` points to `Listing#show` instead of `Listing#index` after sending an HTTP Post request to `Listing#follow` or `Listing#unfollow` to complete the Watch/Unwatch actions.

**Comment by erikcaineolson** [comment]
This is now going back to `Listing#index`, but the filters are not preserved.
